# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyUniversalApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  # Pods for MyUniversalApp

  target 'MyUniversalAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyUniversalAppUITests' do
    # Pods for testing
  end

end
